Added munin to nginx

diff --git a/setup/containers/munin_monitor_postsetup b/setup/containers/munin_monitor_postsetup
--- a/setup/containers/munin_monitor_postsetup
+++ b/setup/containers/munin_monitor_postsetup
@@ -1,12 +1,56 @@
-# if proxy is apache2; then ....
-cat <<EOF > /tmp/munin
-<Location /munin>
-  Require all granted
-  ProxyPass "http://${IP}/munin"
-  ProxyPassReverse "http://${IP}/munin"
-</LOcation>
+# Maybe source parse_config.sh
+PROXY=$(cat configs/containers.json| jq -r .proxy)
+
+if [[ $PROXY == "nginx" ]];
+then
+#if proxy is nginx ;
+  cat <<EOF > /tmp/munin
+    # Proxy pass to servlet container
+
+    location /munin {
+      proxy_pass                http://${IP}/munin;
+      proxy_redirect            off;
+      proxy_set_header Host \$host;
+      proxy_set_header X-Real-IP \$remote_addr;
+      proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
+      proxy_set_header X-Forwarded-Proto  \$scheme;
+	  proxy_hide_header X-Frame-Options;
+      proxy_hide_header Strict-Transport-Security;
+      proxy_hide_header X-Content-Type-Options;
+      proxy_hide_header X-XSS-protection;
+	  proxy_hide_header X-Powered-By;
+	  proxy_hide_header Server;
+
+      proxy_connect_timeout  480s;
+      proxy_read_timeout     480s;
+      proxy_send_timeout     480s;
+
+      proxy_buffer_size        128k;
+      proxy_buffers            8 128k;
+      proxy_busy_buffers_size  256k;
+   }
 EOF
 
-lxc file push /tmp/munin proxy/etc/apache2/upstream/munin
-lxc exec proxy -- service apache2 reload
+  lxc file push /tmp/munin proxy/etc/nginx/upstream/munin
+  rm /tmp/munin
+  
+  lxc exec proxy -- service nginx reload
+elif [[ $PROXY == "apache2" ]];
+then
+#if proxy is apache2 ;
+  cat <<EOF > /tmp/munin
+  <Location /munin>
+    Require all granted
+    ProxyPass "http://${IP}/munin"
+    ProxyPassReverse "http://${IP}/munin"
+  </LOcation>
+EOF
+
+  lxc file push /tmp/munin proxy/etc/apache2/upstream/munin
+  lxc exec proxy -- service apache2 reload
+else
+  echo "Error: Proxy type not supported"
+  exit 1
+fi
+
 
